version: '2'
services:
  node:
    image: xataz/node:7
    container_name: chat-node
    depends_on:
      - database
    links:
      - database:database
    environment:
      - ENV=development
      - "FLARUM_API_ENDPOINT=${FLARUM_API_ENDPOINT}"
      - COOKIES_SECRET=Xpg29n6s9hGuKqWA24U3w5gBAD46yw5X
      - SESSION_SECRET=4fQ9FMEGqYSw3d289h72zx7S4hytb6BG
      - REDIS_URL=redis://database:6379
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    working_dir: /usr/src/app
    command: npm start

  database:
    image: redis:3.2-alpine
    container_name: chat-redis
    command: redis-server --appendonly yes
