chat:
  image: mondedie/chat
  # build: .
  environment:
    - AUTH_API_ENDPOINT=http://domain.tld/api/auth.php
    - ENV=production
    - COOKIES_SECRET=xxxxxxxxxxx
    - SESSION_SECRET=yyyyyyyyyyy
    - REDIS_URL=redis://localhost:6379
  ports:
    - "5000:5000"
  links:
    - redis:redis
    - web:web

redis:
  image: xataz/redis:3.0.5 

web:
  image: nginx:1.9.6
