chat:
  image: xataz/node:6
  container_name: chat
  links:
    - redis:redis
  environment:
    - "AUTH_API_ENDPOINT=${AUTH_API_ENDPOINT}"
    - COOKIES_SECRET=Xpg29n6s9hGuKqWA24U3w5gBAD46yw5X
    - SESSION_SECRET=4fQ9FMEGqYSw3d289h72zx7S4hytb6BG
    - REDIS_URL=redis://redis:6379
  volumes:
    - "${PATH_MONDEDIE_CHAT}/mondedie-chat:/usr/src/app"
  ports:
    - "5000:5000"
  working_dir: /usr/src/app
  command: npm start

redis:
  image: redis:3.0.7-alpine
  container_name: redis
  command: redis-server --appendonly yes
  volumes:
    - /mnt/docker/redis/db/:/data

nginx:
  image: xataz/nginx:mainline
  container_name: nginx
  links:
    - chat:chat
  ports:
    - "80:8000"
  volumes:
    - "${PATH_MONDEDIE_CHAT}/mondedie-chat/nginx/sites-enabled:/sites-enabled"
    - "${PATH_MONDEDIE_CHAT}/mondedie-chat/nginx/log:/var/log/nginx"
