chat:
  image: xataz/node:6
  container_name: chat
  links:
    - redis:redis
  environment:
    - ENV=development
    - "AUTH_API_TOKEN=${AUTH_API_TOKEN}"
    - "AUTH_API_ENDPOINT=${AUTH_API_ENDPOINT}"
    - COOKIES_SECRET=Xpg29n6s9hGuKqWA24U3w5gBAD46yw5X
    - SESSION_SECRET=4fQ9FMEGqYSw3d289h72zx7S4hytb6BG
    - REDIS_URL=redis://redis:6379
  volumes:
    - "${PATH_MONDEDIE_CHAT}/mondedie-chat:/usr/src/app"
  ports:
    - "5000:5000"
  working_dir: /usr/src/app
  command: npm start

redis:
  image: redis:3.2-alpine
  container_name: redis
  command: redis-server --appendonly yes
